server:
  port: 9002
spring:
  config:
    import: optional:configserver:http://config-service
  #zipkin: http://127.0.0.1:9411/
  datasource:
    url: jdbc:mysql://mysql:3306/user-service
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: "*"